name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test

    - name: Test CLI commands (basic smoke test)
      run: |
        chmod +x ./bin/run.js
        ./bin/run.js --version
        ./bin/run.js --help
        ./bin/run.js ping --help
        ./bin/run.js start --help